calculation/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.index, name='index'),
    # ex: /archive/
    url(r'^archive/$', views.archive, name='archive'),
    # ex: /5/
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /new/
    url(r'^new/$', views.new, name='new'),
    # ex: /5/edit/
    #url(r'^(?P<post_id>[0-9]+)/edit/$', views.edit, name='edit'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^accounts/login/profile/edit/', views.profile_edit, name='profile_edit'),
    url(r'^accounts/login/profile/', views.profile, name='profile'),
    url(r'^accounts/login/', views.login, name='login'),    
    url(r'^accounts/logout/', views.logout, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^(?P<user_name>[a-z]+)/', include('calculation.urls', namespace="calculation"), name='user'),
    url(r'', include('calculation.urls', namespace="calculation")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculation/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings

class Post(models.Model):
    author = models.ForeignKey('extuser.ExtUser')
    title = models.CharField(max_length=25)
    url = 'calculation/'
    file = models.FileField(upload_to=url, blank=True)
    file_name = models.CharField(max_length=50, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    delete_date = models.DateTimeField()
    csi = models.FloatField(default=0)
    loyalty = models.FloatField(default=0)
    regress = models.FloatField(default=0)
    one = models.FloatField(default=0)
    two = models.FloatField(default=0)
    three = models.FloatField(default=0)
    four = models.FloatField(default=0)
    five = models.FloatField(default=0)
    
    def publish(self):
        self.created_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

calculation/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'file',)

calculation/views.py
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from django.shortcuts import redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.conf import settings
from django.core import management
import csv
import pprint
from django.contrib.auth.decorators import login_required
from extuser import models

#для регрессии
from pandas import read_csv
import sklearn.linear_model as lm



@login_required
def index(request):
    latest_post_list = Post.objects.order_by('-created_date').filter(author=request.user)
    context = {'latest_post_list': latest_post_list}
    return render(request, 'calculation/index.html', context)

@login_required
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'calculation/detail.html', {'post': post})

@login_required
def archive(request):
    latest_post_list = Post.objects.order_by('-created_date').filter(author=request.user)
    archive_latest_post_list = latest_post_list.filter(delete_date='')
    context = {'archive_latest_post_list': archive_latest_post_list}
    return render(request, 'calculation/archive_index.html', context)

@login_required
def new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created_date = timezone.now()
            post.file_name = post.file.name
            post.save()
            table = []
            table = handle_uploaded_file(request.FILES['file'])
            post.csi = count_csi(table)
            post.loyalty = count_loyalty(table)
            [post.one,post.two,post.three,post.four,post.five] = count_group(table)
            post.save()
            #
            tb = read_csv('mysite/media/calculation/' + request.FILES['file'].name,';')
    
            post.regress = regress(tb)
            post.save()
            return render(request, 'calculation/detail.html', {'post': post})
            #return redirect('/detail/', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'calculation/new.html', {'form': form})

##@login_required
##def edit(request,post_id):
##    post = get_object_or_404(Post, pk=post_id)
##    if request.method == 'POST':
##        form = PostForm(request.POST, request.FILES, instance=post)
##        if form.is_valid():
##            #form.save()
##            post=form.save(commit=False)
##            post.author = request.user
##            post.created_date = timezone.now()
##            post.save()
##            file_field=request.FILES['file']
##            table = []
##            table = handle_uploaded_file(file_field)
##            #pprint.pprint(table)
##            post.csi = count_csi(table)
##            post.loyalty = count_loyalty(table)
##            [post.one,post.two,post.three,post.four,post.five] = count_group(table)
##            post.save()
##            
##            print(post.one,post.two,post.three,post.four,post.five)
##            return render(request, 'calculation/detail.html', {'post': post})
##            #return redirect('/detail/', pk=post.pk)
##    else:
##        form = PostForm(instance=post)
##    return render(request, 'calculation/edit.html', {'form': form})

"""считываем данные с загруженного файла"""
def handle_uploaded_file(f):
    """запись в новый файл
    url = 'mysite/media/' + request.user.myURL + '.csv'
    with open(url, 'wb+') as infile:
        for chunk in f.chunks():
            infile.write(chunk)
    """
    url = 'mysite/media/calculation/' + f.name
    myfile = open(url, 'r')
    table = []
    
    table = [row for row in csv.reader(myfile,delimiter=';')]
    myfile.close()


    for r in range(1,len(table)):
        for c in range(0, len(table[0])):
            table[r][c] =  float(table[r][c])
#считаем средние по столбцам и записываем их в конец таблицы
    row = [0.0]*len(table[0])
    for c in range(0, len(row)):
        s = 0
        k = 0
        for r in range(1, len(table)):
            k += 1
            s += table[r][c]
        row[c] = round(s*10/k, 1)
    table.append(row)
   
    return table

""" запись в файл не надо, не храним файлы
    outfile = open('mysite/media/example.csv', 'w')
    writer = csv.writer(outfile,delimiter=',')
    for row in table:
        writer.writerow(row)
    outfile.close()
"""

def count_csi(table):
    csi = 0
    r = len(table)
    for c in range(1, 4):
        csi += table[r-1][c-1]
    csi = csi/3
    return round(csi,0)

def count_loyalty(table):
    loyalty = 0
    r = len(table)
    for c in range(4, 7):
        loyalty += table[r-1][c-1]
    loyalty = loyalty/3
    return round(loyalty,0)

def count_group(table):
    one = 0
    two = 0
    three = 0
    four = 0
    five = 0
    for r in range(1,len(table)-1):
        csi = 0
        loy = 0
        for c in range(0, 3):
            csi += table[r][c]
        csi = csi*10/3
        #print(csi)
        for c in range(3, 6):
            loy += table[r][c]
        loy = loy*10/3
        #print(loy)
        if csi <= 55:
            if loy <= 55:
                one += 1
                #print(1)
            else:
                three += 1
                #print(3)
        else:
            if loy <= 55:
                two += 1
                #print(2)
        if (loy>=75) and (csi>=75):
            four += 1
            #print(4)
    five = len(table)-2-one-two-three-four
    one = round(one/len(table)*100,1)
    two = round(two/len(table)*100,1)
    three = round(three/len(table)*100,1)
    four = round(four/len(table)*100,1)
    five = round(five/len(table)*100,1)
    return [one,two,three,four,five]




def regress(tb):
    x_csi = (tb['CSI1']+tb['CSI2']+tb['CSI3'])/3
    y_loy = (tb['Loyalty1']+tb['Loyalty2']+tb['Loyalty3'])/3
    x=x_csi.values.reshape(-1,1)
    y=y_loy.values.reshape(-1,1)
    # создаем пустую модель
    skm = lm.LinearRegression()
    # запускаем расчет параметров для указанных данных
    skm.fit(x, y)
    # и выведем параметры рассчитанной модели
    print(skm.intercept_, skm.coef_)
    return skm.coef_

calculation/templates/calculation/!del_edit.html
{% extends 'calculation/base.html' %}
{% block content %}

<div class="post">

	<h1>Редактирование</h1>
	<p>нет редактирования, только удаление??</p>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="" method="POST" enctype="multipart/form-data" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Save</button>
	</form> 

</div>
{% endblock content %}

calculation/templates/calculation/archive_index.html
{% extends 'calculation/base.html' %}
{% block content %}
{% load staticfiles %}  

	{% if archive_latest_post_list %}

	    {% for post in archive_latest_post_list %}
	    
	    <div class="post_index">

			<div class="date">
	             {{ post.created_date }}
			</div>

	        <h1><a href="{% url 'calculation:detail'  post.id %}">{{ post.title}}</a></h1>

				<div class="csi_index" >
					
						<img id="csi_index_meter_needle" src="{% static 'img/calculation/svg-meter-gauge-needle.svg'%}" alt="">
						
					<img src="{% static 'img/calculation/schet.png'%}"/>

					<input id="slider"  value="{{post.csi}}"/>
					<p>CSI: {{post.csi}}</p>
			    		

				</div>


				<div class="loy_index">
					<div>
						<img id="loy_index_meter_needle" src="{% static 'img/calculation/svg-meter-gauge-needle.svg'%}" alt="">
					</div>
					<img src="{% static 'img/calculation/schet.png'%}"/>
					<p>Loyalty: {{post.loyalty}} <input id="slider"  value="{{post.loyalty}}"/></p>
			    		

				</div>
	    </div>

	    {% endfor %}

	    <script src="{% static 'js/calculation/script_index.js'%}"></script>
	
	{% else %}
	    <p>No calculations are available.</p>
	{% endif %}

{% endblock content %}

calculation/templates/calculation/base.html
{% load staticfiles %}
<html>
    <head>
        <title>EPSI</title>
	   <!--  <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css"> -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
      <!--   <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
        <link rel="stylesheet" href="{% static 'css/calculation/post.css' %}">
    </head>
    
    <body>

	<div class="page-header">
	    {% if user.is_authenticated %}
		<a href="{% url 'logout' %}" class="top-menu">logout</a>
		<a href="{% url 'calculation:index'  %}">
			<img style="height:90px" src="{% static 'img/calculation/logo_stand.png'%}" />
		</a>
		<p class="top-title">Барометр лояльности клиентов</p>
	    {% else %}
		<img style="height:90px" src="{% static 'img/calculation/logo_stand.png'%}" />
	    {% endif %}
	</div>

	    <div class="page-left">
	    	{% if user.is_authenticated %}
			<p>Пользователь:</p>
			<a href="{% url 'profile' %}"><p>{{user.firstname}} {{user.lastname}}</p></a>
			<p><center><a href="{% url 'calculation:new'  %}" class="top-menu-left">Загрузить</a></center></p>
			<p><center><a href="{% url 'calculation:archive'  %}" class="top-menu-left">Архив</a></center></p>
			<p><center>До конца лицензии {{user.day_licenz}} дней</center></p>
		    {% endif %}
	    </div>


		<div id="wrapper">
			<div>
			    {% if user.is_authenticated %}
				<img style = "position: fixed; " src="{% static 'img/calculation/fon.jpg'%}" />
			    {% else %}
				
			    {% endif %}
			</div>
			<div class="container">
				<div class="row">
					<div class="col-md-8">
					<center>
					{% block content %}
					{% endblock %}
					</center>
                	</div>
				</div>
			</div>
		</div>


	<footer></footer>
    </body>
</html>

calculation/templates/calculation/detail.html
{% extends 'calculation/base.html' %}
{% block content %}
{% load staticfiles %}

<div class="post">
        <div class="date">
                {{ post.created_date }}
        </div>
	

	<h1>{{ post.title}}</h1>
	<p>Автор: {{ post.author }}</p>
	<p>Расчет произведен по файлу {{ post.file_name }} загруженному в {{ post.created_date }}</p>

	<div class="csi" >
		
			<img id="csi_meter_needle" src="{% static 'img/calculation/svg-meter-gauge-needle.svg'%}" alt="">
			
		<img src="{% static 'img/calculation/schet.png'%}"/>

		<input id="slider"  value="{{post.csi}}"/>
		<p>Индекс удовлетворенности: {{post.csi}}</p>
    		<script src="{% static 'js/calculation/script.js'%}"></script>

	</div>


	<div class="loy">
		<div>
			<img id="loy_meter_needle" src="{% static 'img/calculation/svg-meter-gauge-needle.svg'%}" alt="">
		</div>
		<img src="{% static 'img/calculation/schet.png'%}"/>
		<p>Индекс лояльности: {{post.loyalty}} <input id="slider"  value="{{post.loyalty}}"/></p>
    		<script src="{% static 'js/calculation/script.js'%}"></script>

	</div>

	<p>При увеличении удовлетворенности на <input id="" value=1></p> лояльность изменится на {{post.regress}}</p>
	<div class="example2">
		<h3>Матрица прогноза будущих продаж:</h3>
		<img src="{% static 'img/calculation/matr.png'%}"/>
		<span>
		<p id = "gr_one">{{ post.one }}%</p>
		<p id = "gr_two">{{ post.two }}%</p>
		<p id = "gr_three">{{ post.three }}%</p>
		<p id = "gr_four">{{ post.four }}%</p>
		<p id = "gr_five">{{ post.five }}%</p>
		</span>
	</div>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</div>
{% endblock content %}

calculation/templates/calculation/edit.html
{% extends 'calculation/base.html' %}
{% block content %}

<div class="post">

	<h1>Редактирование</h1>
	<p>нет редактирования, только удаление??</p>

	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

	<form action="" method="POST" enctype="multipart/form-data" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Save</button>
	</form> 

</div>
{% endblock content %}

calculation/templates/calculation/index.html
{% extends 'calculation/base.html' %}
{% block content %}
{% load staticfiles %}  

	{% if latest_post_list %}

	    {% for post in latest_post_list %}
	    
	    <div class="post_index">

			<div class="date">
	             {{ post.created_date }}
			</div>

	        <h1><a href="{% url 'calculation:detail'  post.id %}">{{ post.title}}</a></h1>

				<div class="csi_index" >
					
						<img id="csi_index_meter_needle" src="{% static 'img/calculation/svg-meter-gauge-needle.svg'%}" alt="">
						
					<img src="{% static 'img/calculation/schet.png'%}"/>

					<input id="slider"  value="{{post.csi}}"/>
					<p>CSI: {{post.csi}}</p>
			    		

				</div>


				<div class="loy_index">
					<div>
						<img id="loy_index_meter_needle" src="{% static 'img/calculation/svg-meter-gauge-needle.svg'%}" alt="">
					</div>
					<img src="{% static 'img/calculation/schet.png'%}"/>
					<p>Loyalty: {{post.loyalty}} <input id="slider"  value="{{post.loyalty}}"/></p>
			    		<script src="{% static 'js/calculation/script_index.js'%}"></script>

				</div>

	    </div>

	    {% endfor %}

	{% else %}
	    <p>No calculations are available.</p>
	{% endif %}

{% endblock content %}

calculation/templates/calculation/new.html
{% extends 'calculation/base.html' %}

    {% block content %}

<div class="post">

        <h1>Новый пост</h1>

        <form method="POST" enctype="multipart/form-data" class="post-form">
        	{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>

</div>
{% endblock %}